version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_FOO: "foo"
    working_dir: /app
    ports:
      - "3000:3000"
    image: t3-app
    environment:
      # If you are running your database on localhost in dev, replace `localhost` with `host.docker.internal`
      - DATABASE_URL=postgresql://postgres:changeme@host.docker.internal:5432/t3docker1?schema=public